# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Alper Çaktuğ
title: Senior Test Engineer
email: alpercaktug@outlook.com
#website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: never

# Social links
#twitter_username: facespics
github_username: alpercaktug
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: alpercaktug
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
  - title: itsgoingto.be
    icon: fas fa-globe
    url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

#Google Analytics and Tag Manager
#Using more than one of these may cause issues with reporting
#gtm: "GTM-0000000"
#gtag: "UA-00000000-0"
#google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi,<br> 
  I am an experienced QA Engineer, specializing in designing and implementing robust test automation frameworks.<br>
  My expertise includes UI, API, and mobile test automation, behavior-driven development, CI/CD pipeline integration, and test strategy development.
  I’m passionate about enhancing software quality, improving test strategies, and continuous testing.<br>

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: HotelRunner
        link: hotelrunner.com
        link_text: hotelrunner.com
        sub_title: Test Automation Engineer
        caption: February 2024 - Present
        #quote: >
        # Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          In my role as a Test Automation Engineer at HotelRunner, I led the design and implementation of a scalable test automation framework using Ruby, Selenium, and Cucumber. 
          By seamlessly integrating this framework into the CI/CD pipelines, I optimized workflows, automated test executions, and added detailed reports to increase overall efficiency.
          My contributions to the test strategy also played a key role in enhancing the quality of the SDLC.<br><br>

          • Designed and implemented test automation framework from scratch using Ruby, Selenium, and Cucumber.<br>
          • Integrated test automation into CI/CD pipelines with Jenkins, BrowserStack, and GitHub Actions for seamless execution.<br>
          • Established cross-browser, parallel execution, and rerun strategies to improve test reliability and execution time.<br>

      - layout: left
        title: Payten
        link: payten.com
        link_text: payten.com
        sub_title: Software Development Engineer in Test
        caption: March 2021 - February 2024
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          In my role as a Software Development Engineer in Test at Payten, I responsible for developing and maintaining a robust test automation framework for a high-traffic payment gateway. 
          I automated critical testing processes to enhance test clarity and coverage. 
          This resulted in increased efficiency and reliability of the payment gateway system, ensuring a seamless user experience for customers.<br><br>

           • Developed and maintained test automation framework for a high-traffic payment gateway.<br>
           • Automated browser testing with Selenium (Java) and API testing with RestAssured.<br>
           • Created BDD test scenarios with Cucumber to enhance test clarity and coverage.<br>

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Dokuz Eylül University
        caption: 2016 - 2021
        sub_title: BSc Computer Science
        description: | # this will include new lines to allow paragraphs
            During my time at DEU, I gained a strong foundation in computer science, covering core topics such as algorithms, data structures, object-oriented programming, and database management.
            My coursework also included software engineering, artificial intelligence, computer networks, and cybersecurity, providing me with a well-rounded technical background.<br><br>

            Additionally, I developed hands-on experience in programming languages like Java, C, and Python through various projects and assignments.
            I also explored web development, mobile application development, and cloud computing, which enhanced my understanding of modern software technologies.<br><br>

            Beyond academics, I was an active member of the *DEU Computer Science Club*, where I collaborated on projects, attended seminars, and participated in coding competitions.  

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
